# Generated by Django 3.0.7 on 2020-12-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('Emp_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
